### ISSUE TITLE
Chapter 1 Cleanup

### ISSUE THREAD

**Issue by adowling2** [ndcbe/data-and-computing#16]
Chapter 1: Python Primer

https://ndcbe.github.io/data-and-computing/notebooks/01-publish/01-Jupyter-Notebooks.html
- Done
- [x] Make a checklist if an item needs to be fixed

**Comment by E-Ream** [comment]
@adowling2 @jkeane14 
When we are cleaning up these chapters that have been published on a new branch, do we edit the chapter 01 notebooks or the chapter 01-publish notebooks in jupyter lab?

**Comment by adowling2** [comment]
01 folder. The notebooks in 01-publish are automatically generated.

**Comment by adowling2** [comment]
@E-Ream

Can we split [this notebook](https://ndcbe.github.io/data-and-computing/notebooks/02-publish/03-LU-Factorization.html#errors-in-linear-systems) in two? Split off "Errors in Linear Systems" and the following content to be its own (short) notebook. You'll also need to split the takeaway messages. The first two items stay with LU decomposition. The last takeaway message stays with Errors in Linear Systems.

**Comment by E-Ream** [comment]
@adowling2 Yes, I can do that.  I'll get to work on it next week.

**Comment by adowling2** [comment]
@E-Ream After a bunch of tinkering today, I got LaTeX in the activity callout boxes working:

![Screen Shot 2022-07-05 at 3 35 02 PM](https://user-images.githubusercontent.com/13946870/177402478-77536979-c740-49e2-aae4-bce4253e48e0.png)

https://ndcbe.github.io/data-and-computing/notebooks/01/00-Python-Primer.html

You'll, unfortunately, need to update all of the activity box cells. Click the "Colab" button in the above link to see the new syntax for the cells. Post here with your questions.

**Comment by adowling2** [comment]
Additional clean-up tasks:
- [ ] Pseudocode: Remove "TODO: Add another ..."
- [ ] Rename "Functions, Scoping, and Other Fun Stuff" to "Modules and Files"

**Comment by adowling2** [comment]
@E-Ream I have some ideas I want to try on updating the processing script to automatically formate the home, tutorial, and class activities. Let me prototype a few ideas before you get too far along. I hope to show you a working solution during our meeting this week.

**Comment by adowling2** [comment]
@E-Ream The updated processing script works! Please add to the agenda for the next meeting reformatting notes. I want to add a new type of callout box.

**Comment by adowling2** [comment]
Here are more cleanup requests for Chapter 1:

https://ndcbe.github.io/data-and-computing/notebooks/01-publish/07-Matplotlib.html#matplotlib-basics
- [ ] Remove "Publication Quality Plots" (this will be a separate page added later)
- [ ] Promote "Customizing Plots" and "Plotting Multiple Lines" to level 2 headers
- [ ] Add level 2 header "Learning More" and include links to matplotlib documentation
  - [ ] Tutorials: https://matplotlib.org/stable/tutorials/index.html
  - [ ] Getting Started: https://matplotlib.org/stable/tutorials/introductory/usage.html
  - [ ] Examples: https://matplotlib.org/stable/gallery/index.html

All notebooks:
- [ ] Remove "CBE 20258. Numerical and Statistical Analysis. Spring 2020." or similar text near the top. I'll update the processing script to inject custom text here.

**Comment by adowling2** [comment]
- [ ] Check the headers on this file. Only the title should have a `#`. I think there are a few `#` headers in the middle of the file that should become `##`. Subsequent headers may also need an extra `#`.

**Comment by E-Ream** [comment]
@adowling2 In reference to the headers on the 01-10 notebook, I had fixed this header issue early last week.  Did you republish the chapters before seeing this error or is this for the original publish notebook file?

**Comment by adowling2** [comment]
These are the headers on the main branch. If we have changes on a branch that have not been merged, those changes are not reflected in the header output I posted.

**Comment by E-Ream** [comment]
Okay, that makes sense.  Thank you.

**Comment by adowling2** [comment]
A few more issues after publishing Draft 2:

https://ndcbe.github.io/data-and-computing/notebooks/01-publish/07-Matplotlib.html
  - [ ] Fix links for tutorials, Getting Started, and Examples
