### ISSUE TITLE
Experiment with TOC numbering

### ISSUE THREAD

**Issue by adowling2** [ndcbe/data-and-computing#33]
https://jupyterbook.org/en/stable/structure/configure.html#toc-numbering

**Comment by adowling2** [comment]
This might get complicated: https://jupyterbook.org/en/stable/structure/sections-headers.html#toc-structure

**Comment by jckantor** [comment]
The docs are a little intimidating, but it's really pretty straightforward. Here's an example for a project I'm involved with ... https://github.com/jckantor/MO-book/blob/main/_toc.yml.  The format is very particular about indentations and the space between the "-" and "file:", and the space following the colon.
