### ISSUE TITLE
Chapter 5 Cleanup

### ISSUE THREAD

**Issue by jkeane14** [ndcbe/data-and-computing#42]
Continuous Optimization:

Pyomo Basics:
- [x] remove CBE 2020 at top
- [x]  ipopt could not be located in first example
- [x] fix formatting in cherry tree example

Electricity Marketing Optimization:
- [x] remove CBE 2020 at top
- [x]  ipopt not downloading correctly
- [ ]  image not appearing on website

Flash Calculations in Pyomo:
- [x] remove CBE 2020 at top

**Comment by adowling2** [comment]
Just change it to USD (US dollars) if the symbol is for money.

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/05-publish/01-Pyomo-Basics.html
- [ ] Update the URLs for the two motivating examples by removing the token. For example, https://www.sciencedirect.com/science/article/pii/S0098135404001565 instead of the longer URL you are currently using.
