### ISSUE TITLE
Chapter 11 Cleanup

### ISSUE THREAD

**Issue by adowling2** [ndcbe/data-and-computing#44]
Fix headers (if not done already):

```
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/11-publish/02-Standard-Normal-Distribution.ipynb:80002: WARNING: Non-consecutive header level increase; 2 to 4 [myst.header]
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/11-publish/02-Standard-Normal-Distribution.ipynb:100002: WARNING: Non-consecutive header level increase; 2 to 4 [myst.header]
```

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/11-publish/01-Central-Limit-Theorem.html
- [ ] Replace "Central Limit Theorem" header with "Introduction"
- [ ] Promote headers one level
- [ ] Move reference to the top of the page.
- [ ] For links to the documentation, replace the URL with the word "document" hyperlinked.
- [ ] Remove "CLT" from "Illustrative Example: Membrane Defects"

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/11-publish/03-Confidence-Intervals.html
- [ ] Replace "Confidence Interval" with "Definition and Formula" in header
- [ ] Replace "Motivating Example: Catalyst Life" with "Motivation: Catalyst Life Example"
- [ ] Remove "68-95-99.7 Rule" and "Confidence Interval Formula" subheaders, add a sentence to introduce/explain the content.
- [ ] Replace "Catalyst Life Example" with "Example Calculation", promote to level 2 header

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/11-publish/04-Students-t-Distribution.html
- [ ] Remove "Student’s t-Distribution" level 2 header
- [ ] Promote level 3 subheaders to level 2
- [ ] Shorten subheader to "Important Assumptions"
- [ ] Replace the Process 1 and Process 2 images with Python code. Use an auto-regressive 1 model. 

For an AR1 model, assume for process 1:

r = 0.2
sigma = 0.1
yield[i] = (1-r)*a*sin(t*b) + normal(0,sigma) + r*yield[i-1]

You can adjust a and b to get reasonable values for yield between 0 and 1

For AR1 model, assume for process 2:

r = 0.2
sigma = 0.1
yield[i] = (1-r)*0.5 + normal(0,sigma) + r*yield[i-1]

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/11-publish/05-First-Hypothesis-Testing.html#hypothesis-testing
- [ ] Change title to "Hypothesis Testing Basics"
- [ ] Move references to top of the notebook.
- [ ] Replace "Hypothesis Testing" with "Main Idea", promote to level 2 header, remove "Main Idea:" from the paragraph, add link to flavors of hypothesis testing
- [ ] Promote all headers one level. Want mainly level 2 headers. (Okay for steps to be level 3.)

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/11-publish/07-Flavors-of-Hypothesis-Testing.html
- [ ] Move this to before Type I and Type II errors in the TOC
- [ ] In the introduction, clarify the section references in the table are for Navidi (2015)

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/11-publish/08-Statistical-Power-Basics.html
- [ ] Add reference to Navidi section to the top of the page
- [ ] Replace "Statistical Power" subheader with "Definition"
- [ ] Promote "Motivating Example" to level 2 header
- [ ] Promote steps to level 2 header
- [ ] Draw step 2 and step 3 plots in Python, hide code in webpage using cell tags

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/11-publish/09-Statistical-Power-in-Python.html
- [ ] Split the "meat" of the notebook into "Documentation and References" (with the links) and "Example Revisited" (with the code)

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/11-publish/10-Statistical-Power-Practice-Problems.html
- [ ] Promote all the subheaders (except learning objectives) one level. This means each practice problem will be level 2
- [ ] Promote given data and parts 1 - 6 in problem C to level 3 subheaders
- [ ] Give the practice problems meaningful names. Such as "Conceptual Understanding" and "Statistical Power Calculations"

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/12-publish/01-Ordinary-Least-Squares-Linear-Regression.html
- [ ] Remove Correlation and Best Fit Line subsections, move references to "Motivating Example" section

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/12-publish/02-Uncertainty-Analysis-and-Statistical-Inference.html
- [ ] Replace "Uncertainty Analysis and Statistical Inference" with "Main Idea"
- [ ] Promote level 3 headers to level 2
- [ ] Remove "CBE 20258. Numerical and Statistical Analysis. Spring 2020. © University of Notre Dame" from the top

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/12-publish/04-Multivariate-Linear-Regression.html
- [ ] Remove "Multivariate Regression" level 2 header
- [ ] Promote the headers from level 3 to level 2
- [ ] Adjust the table of contents so this page comes before the uncertainty analysis page.

**Comment by jkeane14** [comment]
@adowling2 Hi Prof Dowling, just wanted to confirm that I should be working on further edits for this chapter from the Chapter-11-Cleanup branch from this point on

**Comment by adowling2** [comment]
Yes, just make sure you pull updates from the sender onto your local computer. Before starting, confirm the notebooks look good (e.g., contain your prior edits). Post here is you have any questions or encounter anything strange.

**Comment by adowling2** [comment]
@jkeane14 I'll investigate this more. I *thought* the script I ran merged them. Standby. I might not get to this until after 3 pm today.

**Comment by adowling2** [comment]
Posting here mainly for my future reference:
- I originally resolved the merge conflicts with [nbdev](https://nbdev.fast.ai/merge.html). That overwrote changes from @jkeane14 
- I am now trying [nbdime](https://nbdime.readthedocs.io/en/latest/installing.html) to compare/manually merge the notebooks.
- [This post](https://stackoverflow.com/questions/62325068/cannot-install-latest-nodejs-using-conda-on-mac) was helpful when installing the dependency `node.js`.

**Comment by adowling2** [comment]
@E-Ream Do not change any of the Chapter 11 notebooks (besides creating the bootstrap one). I am in the process of recovering edits from @jkeane14. I'll update here when I am done.

**Comment by E-Ream** [comment]
I'm tracking on that, just created the bootstrap notebook today but it shouldn't have edited any of the other notebooks.

**Comment by adowling2** [comment]
Great! We also have two live branches for chapter 11 edits. Not a big issue, just something we need to be careful about.

**Comment by adowling2** [comment]
@jkeane14 I recovered your notebooks and added them to this branch:

https://github.com/ndcbe/data-and-computing/tree/Chapter-11-Statistical-Inference/notebooks/11

You'll see the `11` folder is a little cluttered with notebooks. I am differencing them now. I'll report what I find.

**Comment by jkeane14** [comment]
@adowling2  Great! Will I still be making edits to Chapter-11-Cleanup or will I now be working on the Chapter-11-Statistical-Inference branch?

**Comment by adowling2** [comment]
Here are the results in the comparison across versions:
* `01`, `02`, `03`, `05` only metadata changed
* `04` looks like changes were made to versions with and without `'` in the file name. This will likely need to be merged manually.
* `06-Flavors`, `07-Type-I`, `08`, `09`, `10` only meta-data changed

**Comment by adowling2** [comment]
@jkeane14 Which of your changes did you not see propagated in the merge from Friday evening? After restoring the prior versions of your notebooks, I am not seeing any changes except for `04` (see prior post). I think this means the merge on Friday went okay.

Please use the `Chapter-11-Statistical-Inference` branch. That has the restored notebooks with `-JK` added to the file name. You'll need to pull from origin to see these files on your computer.

**Comment by adowling2** [comment]
After you are done with the edits, let's remove the files with `-JK` in the name.

**Comment by adowling2** [comment]
Just to be clear, @jkeane14 is using the `Chapter-11-Statistical-Inference` branch which is linked to PR #69. Meanwhile, @E-Ream is using the `Chapter-11-Cleanup` branch which is linked to PR #73. The latter adds one notebook only. These two branches should not have any conflicts.

**Comment by adowling2** [comment]
I think we got this sorted out!

**Comment by jkeane14** [comment]
Looks good on my end. I will finish up edits on Chapter-11-Statistical-Inference branch. Thanks for figuring this all out.
