### ISSUE TITLE
Chapter 13 Clean Up

### ISSUE THREAD

**Issue by adowling2** [ndcbe/data-and-computing#62]
https://ndcbe.github.io/data-and-computing/notebooks/13-publish/01-Transformations-and-Linear-Regression.html
- [x] Promote level 3 heads to level 2
- [x] Split "Motivating Example and Dataset" into "Motivating Example" and "Dataset"
- [x] Rename "Transformation and Linear Regression", "Step 1: Transformation"
- [x] Promote the steps to level 2 subheaders, increment step number by 1
- [x] Remove: "CBE 20258. Numerical and Statistical Analysis. Spring 2020. © University of Notre Dame" from top

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/13-publish/02-Nonlinear-Regression.html
- [ ] Remove: "CBE 20258. Numerical and Statistical Analysis. Spring 2020. © University of Notre Dame" from top
- [ ] Rename "Nonlinear Regression" as "Main Idea", and remove "Main idea" from the beginning of the text.
- [ ] Link to the previous notebook when explaining the example.
- [ ] Promote the Step subheaders to level 2
- [ ] Rename "Step 1: Calculate and Plot Best Fit"
- [ ] Rename "Step 2: Residual Analysis"
- [ ] Rename "Step 3: Uncertainty Analysis"
- [ ] Update link to 13-01, use the notebook name.

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/13-publish/03-Nonlinear-Regression-Practice-Problem.html
- [ ] Remove: "CBE 20258. Numerical and Statistical Analysis. Spring 2020. © University of Notre Dame" from top
- [ ] Remove "Nonlinear Regression Practice Problem"
- [ ] Change to"For this question, originally developed by [Prof. David T. Leighton](https://engineering.nd.edu/faculty/david-leighton/), you will..." Move this sentence to the next section.
- [ ] Promote "Background" and other subheaders to level 2

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/13-publish/04-Weighted-Regression.html
- [ ] Remove: "CBE 20258. Numerical and Statistical Analysis. Spring 2020. © University of Notre Dame" from top
- [ ] Remove "Weighted Regression" subheader
- [ ] Promote "Michaelis-Menten Modeling Revisited" to level 2 header
- [ ] Link to the previous notebooks that explore this example.
- [ ] Create a level 2 header "Other Approaches", link to the previous notebooks for "Approach 1: Transformation + Linear Regression", just link to the prior notebook" and "Approach 2: Nonlinear Regression"
- [ ] Remove "Approach 1: Transformation + Linear Regression" and "Approach 2: Nonlinear Regression" sections. Instead, add discussion to the new "Other Approaches" discussion. In this new section.
- [ ] Replace "Approach 3: Transformation + Weighted Linear Regression" with "Main Head" level 2 header, remove "Main idea:" from the first sentence
- [ ] Update the notation so vectors and matrices use `\mathbf{y}`, etc.
- [ ] Promote the "Steps" to level 2 headers

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/13-publish/05-Monte-Carlo-Uncertainty-Analysis-for-Nonlinear-Regression.html#simulation
- [ ] Remove: "CBE 20258. Numerical and Statistical Analysis. Spring 2020. © University of Notre Dame" from top
- [ ] Check if "Simulation" content is already in https://ndcbe.github.io/data-and-computing/notebooks/10-publish/05-Simulation.html. If so, remove duplicate content from this Chapter 13 notebook. Add a sentence sending the reader to the Chapter 10 notebook.
- [ ] Create a new notebook in Chapter 10 titled "Monte Carlo Error Propagation". Move the content related to the "Cart + Incline" example to this page. Also add the pencil and paper homework problem to this new page. (I can provide the solutions.)
- [ ] This should leave only content under "Uncertainty Analysis for Nonlinear Regression" in this notebook.
- [ ] Remove "Uncertainty Analysis for Nonlinear Regression" subheader.
- [ ] Promote "Motivating Example: Michaelis-Menten Enzymatic Reaction Kinetics" to level 2 header
- [ ] Link to other pages that analyze this example.
- [ ] Verify the content in "Nonlinear Regression + Linearized Uncertainty Analysis" subsection is redundant with prior notebooks. If so, remove this content and link to the other notebook. Move any superior explanations/content from this notebook to the earlier notebook.
- [ ] Assuming the prior comment is correct (information is redundant), this notebook should only have "Nonlinear Regression + Monte Carlo Uncertainty Analysis" and its content.
- [ ] Replace "Nonlinear Regression + Monte Carlo Uncertainty Analysis"  with "Main Idea". Remove "Main idea:" from the first sentence.
- [ ] Promote "Pseudocode", "Python Hints", ... to level 2 headers. Goal is for all headers in this notebook to be level 2
- [ ] Review and update the learning objectives accordingly

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/13-publish/06-Bootstrap-Confidence-Intervals.html
- [ ] Remove: "CBE 20258. Numerical and Statistical Analysis. Spring 2020. © University of Notre Dame" from top
- [ ] Remove "Bootstrap Confidence Intervals" header.
- [ ] Move references to the top of the notebook
- [ ] Add learning objectives
- [ ] Promote "Motivating Example: Catalyst Lifetime" and other subheaders to level 2.
- [ ] Link to other notebooks that examine this example.
- [ ] Remove "Traditional Confidence Intervals" subheader
- [ ] Change "z-interval" to "z Confidence Interval", level 2
- [ ] Link to the prior page on this
- [ ] Change "t-interval" to "Student's t Confidence Interval", level 2
- [ ] Move this notebook to the prior chapter
- [ ] Add a final "Final Thoughts" level 2 subheader. In this new section, compare the z-, t-, and bootstrap confidence intervals.

**Comment by adowling2** [comment]
https://ndcbe.github.io/data-and-computing/notebooks/13-publish/07-Nonlinear-Case-Study-Adsorptive-Membranes.html
- [ ] Replace "© Elvis A. Eugene and Alexander W. Dowling, University of Notre Dame" with "*Contributors*: [Elvis A. Eugene](https://github.com/elvis1090) and [Alexander W. Dowling](https://github.com/adowling2)"
- [ ] Remove the "A", "B", "C", etc. from the subheaders

**Comment by E-Ream** [comment]
@adowling2 For the 13-05 Monte Carlo notebook, I've created a new notebook in chap 10 for the specified parts.  Could you specify what pencil and paper problem you are referring to that I should add and provide the solutions?

**Comment by E-Ream** [comment]
@adowling2 For the 13-06 notebook, Bootstrap Confidence Intervals, you mention to move it to the previous chapter.  Do you want it in chapter 12 or in chapter 11 with the other confidence interval notebooks?

**Comment by adowling2** [comment]
@E-Ream I think I confused myself. To be explicit,

https://ndcbe.github.io/data-and-computing/notebooks/13-publish/06-Bootstrap-Confidence-Intervals.html

should move to the end of Chapter 11.
